runtime: go116  # or another supported version
service: feedgram-backend
main: ./cmd/main

env_variables:
  GIN_MODE: release
  GO111MODULE: on
  PROJECTID: feedgram-333720
  BUCKETSTORAGENAME: feedgram-images
  PRKEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRGAVpEJZh/CnMpNB9TX8gRSV3LOnVE3G10B9trWd6vqk+1NA04qX6I1oyeKoAt8OejgbieThGavsr9DWTAfMjww2FDt+AIbs5EtIgNf7jIfb3/UNbyTRjX2NI6+d7o8ty9Afk1t66pi9IuroizCYFtwMq3CKiyjYFWxZCrguPaDGf/ts0b+i1+oimJJNg6gDJwmT4CfFgtmtgnfenhkKobdNdl+gD9y/o5X7VQsrUbPE4csNubxmseyHDw+clsVwoD8gu7/qfdpYfW9iaNNedIObPMfBHKL9IquBnIiyavtIqH5Z/tKdRwKQSZn3TH3jK760sFebFE8aIhWBZ0XV7AgMBAAECggEAB56PTT79qTrApS9DqlqWwtdyNY+37Pv6kqGvu4CW+unpY0ZAWLpXn7AGcJIQE9rzxcUu1WA4dOx0vwB1AVM6sndq+InMYDAae/UbyMZe8D+ZGdFV+97ESh4RkU3eD2suaz/Jl9pdScJA39lva1GIIyuCRzS4DbmTqAn5MNsvGv3OlHoFGBBIpjxcUwYvQ6scX6GyibTVhFEbAZeyrXSe4k4HjyvuteqJYVyXRFdv8D5rmtHQngwmH2atbZxW5eq5nMU4f7nUACeYUkj51FJlHWhX5XHaVPgH9ZdN7PixIE5M6nWpjgGz1XgZzmK/bYsZK1q6Wh3f7wcmmurwCGmzmQKBgQD9Dy5zyVZqiovE9VVvxsn8sHieu8tQUuVv7D0AKuNWrZ/kZjycif1Wcig3REV3MZi8W3AVzWmo3mFT/lOyT4ARV4xqIDlcWvN0iW60BLyS1EVs3OMEGgDoWxyrC3IO2SqmnLh3JhBgKbMLsTMRHlo8rZFKZmWczFwn+DymfvHbiQKBgQDThgxRiqVcGOwtJbjvxWRG6LQKS/ZkL8i6tJEaqomfgQEUhD9rOPQVLrUQubOr5FKNYX6VtBdgqrZKlkeK8MgYSlKZt6LDSZyTItaaDkXJWkWoBwYbfIfOCRghkaXsFtxFVzUPjnYcngdG5RlJ+rr5kcacbJXJ2RXrRbUWeEOz4wKBgQCPPk20Gu7ApiYR2jF/cQ4a7CWK7JBcql/XZ+jrtFs1UFimp7x9e5qcmUfsaMfNfZSQYk3i+YBqp15+dgMYdunuZxlDZXQytAUFHVo9qkS39FJMGgii5LlIzXI/2923S/RZlXLRdwlj9Za08pwOf5jiqfkJHUc9Z2xu75QdRtROyQKBgGf0vH8ixcwyj3hMzsxAVd0nprxcwvZQKbXg4mOZptOWYkKEEGsQ7ZyvfNuAeNYk+5FydfT7MnYW0Ept+zFEzwJpHJlhkAOsXOBPQesq0o935z4CXbUKie/vtkVhQIt8XLtTdcd0e4XrAKaOF9Ss/lGDnHnqP9+Y6lXbx3kImDWDAoGAGCMc0mNqYlQVsABS5iIy0gY5AsVJKKPjZEpbZjVSwFEUzJQ74PHSmiPcPoCVu9jxFqpjnJoR/jTeaHo7xOFg2pwYoGPLXf42X00elRr+gB/dvNGHxDYak4YxfTgFY+PPulxCRNgywbWydox1cCbagLAA3BWo7ZyjfNTMSJkN1y8=
handlers:
- url: /login/new_user
  script: main.go

- url: /media/:media_id
  script: main.go

- url: /:user_name
  script: main.go

- url: /:user_name/new_media
  script: main.go

- url: /:user_name/new_post
  script: main.go

- url: /:user_name/get_posts
  script: main.go

- url: /post/:post_id
  script: main.go
